### ISSUE TITLE
Option to highlight note's title on creation

### ISSUE THREAD

**Issue by alltiagocom** [Lisandra-dev/obsidian-create-note-in-folder#15] opened 2023-12-03 13:48 UTC
Thank you for the great plugin!
I started using it yesterday, but one thing I believe will make a big difference is an option (so each user uses it or not based on their preferred workflow) to highlight the title instead of just adding "Untitled" and going straight to the body of the note.
In my case I always like to add a title right away.

Hope you can implement this :)

**Comment by Mara-Li** [comment] 2023-12-03 14:13
Litterally the last update do it. Duplicate of #13

**Comment by alltiagocom** [comment] 2023-12-03 17:16
> Litterally the last update do it. Duplicate of #13

I'm sorry, I'm a bit confused. You mean that the latest update (1.7.0) highlights the title?
If so, I'm not experiencing that. The cursor still goes to the body of the note. I even restarted Obsidian, just in case, but it's not working.

Can you clarify what you mean?
I saw that other issue you shared (#13) and it seems you can't change this behavior, but now you said "the last update do it" so I'm confused about this.
![Kapture 2023-12-03 at 17 18 36](https://github.com/Lisandra-dev/obsidian-create-note-in-folder/assets/96640778/751a3389-7769-4c09-81e2-8f3554fea75c)

I don't know if this is relevant or not:
Obsidian version 1.4.16
macOS 10.15.7

Thanks

**Comment by Mara-Li** [comment] 2023-12-04 00:54
Hm, seems it is not working on your side.
Can I have the settings you use for the folder?

As there isn't a API to do it, I use an hacky way but it worked on my side :(

**Comment by Mara-Li** [comment] 2023-12-04 07:09
Tested on my test vault & normal vault and the note title is hightlighted. Maybed the methods i used doesn't work on MacOS ?

**Comment by alltiagocom** [comment] 2023-12-04 11:12
> Hm, seems it is not working on your side. Can I have the settings you use for the folder?
> 
> As there isn't a API to do it, I use an hacky way but it worked on my side :(

Hope this is what you need
![image](https://github.com/Lisandra-dev/obsidian-create-note-in-folder/assets/96640778/51491980-d4ef-41cf-ae7f-69ea1f344656)

If it doesn't indeed work on macOS, what if the plugin includes an option to show a modal to add the Title? Then when we hit Enter, it will grab that info from the modal and creates the new note using that info, then goes to the body of the note.
That way, as an optional feature, those with a Mac can enable it, and those with Windows can disable it.

**Comment by Mara-Li** [comment] 2023-12-04 12:41
Not, it's not the settings I need : I need the "edit" (on the pencil) parameters.

It's very strange that i didn't work on MacOS without reason. 

Can you try a command without the `{{current}}`, ie in a specific folder ?
Did you have something in the console (CMD+MAJ+I) when you use the command/enable the plugin ?

Your plugin is in 1.8.0 ?

**Comment by Mara-Li** [comment] 2023-12-04 12:49
It even works on my ipad : 

https://github.com/Lisandra-dev/obsidian-create-note-in-folder/assets/30244939/6f423010-8444-4c88-bff3-8d1f15229b30

**Comment by alltiagocom** [comment] 2023-12-04 13:02
**_Not, it's not the settings I need : I need the "edit" (on the pencil) parameters._**
This?
![image](https://github.com/Lisandra-dev/obsidian-create-note-in-folder/assets/96640778/9a387d71-11c4-4d82-b208-77dd135d113f)



**_It's very strange that i didn't work on MacOS without reason_**
I just noticed that 2 of the options work as expected, 1 doesn't.
Green: work, meaning they highlight the title. Red: doesn't, meaning it goes to the body.
![image](https://github.com/Lisandra-dev/obsidian-create-note-in-folder/assets/96640778/b5aea3b7-246d-4387-b9a5-8b4a4dc3dcf5)


**_Can you try a command without the `{{current}}`, ie in a specific folder ?_**
Yes, removing {{current}} and adding a specific folder, makes it work, so it seems that the issue is with {{current}}
We are getting closer now ;)

**_Did you have something in the console (CMD+MAJ+I) when you use the command/enable the plugin ?_**
What you mean by "MAJ"?


_**Your plugin is in 1.8.0 ?**_
Yes, I just updated it, but as mentioned, 1 of them doesn't work.

**Comment by Mara-Li** [comment] 2023-12-04 13:12
So the bug seems to be around the `{{current}}`

The methods used for current is a little bit more hacky than the other methods. I set a timeout of 50, but maybe we need more ?
I will add an option to set the timeout, so we can try editing this option to see if it works

**Comment by Mara-Li** [comment] 2023-12-04 13:20
Okay, I published the 1.18.1, adding a new setting `timeOutForInlineTitle`. 

After updating to this version, try if a bigger value work for you : 
- open the file `data.json` file in `.obsidian/plugins/create-note-in-folder` (any text editor works)
- Edit the value `timeOutForInlineTitle` with a bigger number, like 3000 for example (3000 = 3seconde) 
- Save the file
- Reload the plugin
- Try to create a file in current

**Comment by alltiagocom** [comment] 2023-12-04 14:05
Updated it.
So 99% of the time, the timeout set to 50 would not work. I don't know why sometimes it did, but it's definitely not that reliable.
I found that 100 is more constant and it always works.
I will leave it like that and if by any chance it doesn't work sometimes, I will change it to a higher value and will report it so you can be updated on this as well. 

Thank you so much for your help on this.

**Comment by Mara-Li** [comment] 2023-12-04 15:10
Thank you too for this quick reply and help me debug the issue ! 
I will improve the settings to allow differents timeout by platform (mobile / desktop), make a little update in the README and close the issue after that.

**Closed as completed** 2023-12-04 17:58 UTC
Labels: bug
